name: Hello
on: workflow_dispatch
jobs:
    build:
     runs-on: ubuntu-latest
     steps:
         - name: Hello Mohan
           run: echo "Hello build"
    test:
     runs-on: ubuntu-latest
     steps:
       - name: Hello Mohan
         run: echo "Hello test"
    deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Hello Mohan
         run: echo "Hello deploy"
